import axios from "axios";
const API_GIOHANG = 'http://localhost:8080/api/giohang';
export const listgiohangbyid = (id) => axios.get(API_GIOHANG+ '/' + id);
export const listgiohang = ()=> axios.get(API_GIOHANG);
export const creategiohang = (giohang) =>axios.post(API_GIOHANG,giohang);   
export const deletegiohangbyid = (id)=> axios.delete(API_GIOHANG+ '/' + id);
export const listitemgiohangbyid = (id) => axios.get(API_GIOHANG+ '/item/' + id);
export const updatesoluong = (id,giohang)=> axios.put(API_GIOHANG+ '/' + id,giohang);
export const tongtiengiohang = (id) => axios.get(API_GIOHANG+ '/tongtien/' + id);
export const allsoluonggiohang = (id) => axios.get(API_GIOHANG+ '/allsoluong/' + id);